FROM golang:alpine AS builder
WORKDIR /app
ADD . /app
RUN go build -o /sheltertech-go ./cmd/sheltertech-go

FROM golang:alpine
COPY --from=builder /sheltertech-go /sheltertech-go
CMD ["/sheltertech-go"]