version: "3.5"

services:
  sheltertech-go:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: askdarcel_development
      DB_USER: postgres
    networks:
      - askdarcel
    ports:
      - "3001:3001"
      - "3002:3002"

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - askdarcel
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  # Used to connect to askdarcel in a different docker-compose instance
  askdarcel:
    name: askdarcel