version: "3.5"

services:
  sheltertech-go:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: askdarcel_development
      DB_USER: postgres
      AUTH0_DOMAIN: "dev-nykixf8szsm220fi.us.auth0.com"
    networks:
      - askdarcel
    ports:
      - "3001:3001"
      - "3002:3002"

networks:
  # Used to connect to askdarcel in a different docker-compose instance
  askdarcel:
    name: askdarcel