//go:build integration
// +build integration

package main

import (
	"bytes"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"net/http"
	"os"
	"sync"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

var (
	cachedToken string
	tokenOnce   sync.Once
)

// getTestToken signs a JWT locally using the test RSA private key.
// No Auth0 calls — works in CI and locally when USE_LOCAL_JWT=true.
func getTestToken() string {
	tokenOnce.Do(func() {
		privateKey := loadPrivateKey()

		claims := jwt.RegisteredClaims{
			Subject:   "test_user_external_id",
			Issuer:    os.Getenv("ISSUER_URL"),
			Audience:  jwt.ClaimStrings{os.Getenv("AUTH0_AUDIENCE")},
			ExpiresAt: jwt.NewNumericDate(time.Now().Add(1 * time.Hour)),
			IssuedAt:  jwt.NewNumericDate(time.Now()),
		}

		token := jwt.NewWithClaims(jwt.SigningMethodRS256, claims)
		token.Header["kid"] = "test-key-1"

		signed, err := token.SignedString(privateKey)
		if err != nil {
			panic(fmt.Sprintf("failed to sign test JWT: %v", err))
		}

		cachedToken = signed
	})

	return cachedToken
}

// loadPrivateKey reads the RSA private key generated by `make generate-test-keys`.
func loadPrivateKey() *rsa.PrivateKey {
	keyBytes, err := os.ReadFile("../../test/private_key.pem")
	if err != nil {
		panic(fmt.Sprintf("failed to read test/private_key.pem — did you run `make generate-test-keys`? error: %v", err))
	}

	block, _ := pem.Decode(keyBytes)
	if block == nil {
		panic("failed to decode PEM block from test/private_key.pem")
	}

	key, err := x509.ParsePKCS1PrivateKey(block.Bytes)
	if err != nil {
		panic(fmt.Sprintf("failed to parse RSA private key: %v", err))
	}

	return key
}

// newAuthRequest creates an HTTP request with the Bearer token attached.
func newAuthRequest(method, url string, body *bytes.Buffer) (*http.Request, error) {
	var req *http.Request
	var err error

	if body != nil {
		req, err = http.NewRequest(method, url, body)
	} else {
		req, err = http.NewRequest(method, url, nil)
	}
	if err != nil {
		return nil, err
	}

	req.Header.Set("Authorization", "Bearer "+getTestToken())
	req.Header.Set("Content-Type", "application/json")
	return req, nil
}
