# This workflow builds and pushes a tagged docker image from the main branch
name: publish-release

on:
  push:
    tags:
      - '*'

env:
  DOCKER_REPO: sheltertechsf/sheltertech-go

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=false
            prefix=
            suffix=
          images: |
            ${{ env.DOCKER_REPO }}
          tags: |
            type=semver,pattern={{version}}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - run: echo ${{ steps.docker_build.outputs.digest }}
